apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: jdbc-source-connector
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  config:
    connection.url: jdbc:postgresql://postgresql:5432/accountantsdb?user=postgres&password=postgres
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    topic.prefix: postgre-
    table.whitelist: accountants
    mode: incrementing
    incrementing.column.name: id
    # TODO: Add Single Message Transformations
    transforms: Mask,Insert
    transforms.Mask.type: org.apache.kafka.connect.transforms.MaskField$Value
    transforms.Mask.fields: ssn
    transforms.Insert.type: org.apache.kafka.connect.transforms.InsertField$Value
    transforms.Insert.static.field: data-source
    transforms.Insert.static.value: database
  tasksMax: 1
