apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wind-turbine-production
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824