/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.redhat.training.bank.event.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BankAccountBalanceWasChanged extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8303020593160542138L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BankAccountBalanceWasChanged\",\"namespace\":\"com.redhat.training.bank.event.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"balance\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BankAccountBalanceWasChanged> ENCODER =
      new BinaryMessageEncoder<BankAccountBalanceWasChanged>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BankAccountBalanceWasChanged> DECODER =
      new BinaryMessageDecoder<BankAccountBalanceWasChanged>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BankAccountBalanceWasChanged> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BankAccountBalanceWasChanged> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BankAccountBalanceWasChanged> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BankAccountBalanceWasChanged>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BankAccountBalanceWasChanged to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BankAccountBalanceWasChanged from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BankAccountBalanceWasChanged instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BankAccountBalanceWasChanged fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private long balance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BankAccountBalanceWasChanged() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param balance The new value for balance
   */
  public BankAccountBalanceWasChanged(java.lang.Long id, java.lang.Long balance) {
    this.id = id;
    this.balance = balance;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return balance;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: balance = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'balance' field.
   * @return The value of the 'balance' field.
   */
  public long getBalance() {
    return balance;
  }


  /**
   * Sets the value of the 'balance' field.
   * @param value the value to set.
   */
  public void setBalance(long value) {
    this.balance = value;
  }

  /**
   * Creates a new BankAccountBalanceWasChanged RecordBuilder.
   * @return A new BankAccountBalanceWasChanged RecordBuilder
   */
  public static com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder newBuilder() {
    return new com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder();
  }

  /**
   * Creates a new BankAccountBalanceWasChanged RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BankAccountBalanceWasChanged RecordBuilder
   */
  public static com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder newBuilder(com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder other) {
    if (other == null) {
      return new com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder();
    } else {
      return new com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder(other);
    }
  }

  /**
   * Creates a new BankAccountBalanceWasChanged RecordBuilder by copying an existing BankAccountBalanceWasChanged instance.
   * @param other The existing instance to copy.
   * @return A new BankAccountBalanceWasChanged RecordBuilder
   */
  public static com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder newBuilder(com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged other) {
    if (other == null) {
      return new com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder();
    } else {
      return new com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder(other);
    }
  }

  /**
   * RecordBuilder for BankAccountBalanceWasChanged instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BankAccountBalanceWasChanged>
    implements org.apache.avro.data.RecordBuilder<BankAccountBalanceWasChanged> {

    private long id;
    private long balance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.balance)) {
        this.balance = data().deepCopy(fields()[1].schema(), other.balance);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing BankAccountBalanceWasChanged instance
     * @param other The existing instance to copy.
     */
    private Builder(com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.balance)) {
        this.balance = data().deepCopy(fields()[1].schema(), other.balance);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'balance' field.
      * @return The value.
      */
    public long getBalance() {
      return balance;
    }


    /**
      * Sets the value of the 'balance' field.
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder setBalance(long value) {
      validate(fields()[1], value);
      this.balance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'balance' field.
      * @return This builder.
      */
    public com.redhat.training.bank.event.avro.BankAccountBalanceWasChanged.Builder clearBalance() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BankAccountBalanceWasChanged build() {
      try {
        BankAccountBalanceWasChanged record = new BankAccountBalanceWasChanged();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.balance = fieldSetFlags()[1] ? this.balance : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BankAccountBalanceWasChanged>
    WRITER$ = (org.apache.avro.io.DatumWriter<BankAccountBalanceWasChanged>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BankAccountBalanceWasChanged>
    READER$ = (org.apache.avro.io.DatumReader<BankAccountBalanceWasChanged>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeLong(this.balance);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.balance = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.balance = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










